Repository Step3-kakao-tech-campus/Team5_FE, pull requests merged in 2023-10, with the labels that each got.

#10 회원가입 페이지 구현
  .eslintrc.json
  src/App.js
  src/apis/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/components/signup/atoms/Box.jsx
  src/components/signup/atoms/Button.jsx
  src/components/signup/atoms/Container.jsx
  src/components/signup/atoms/Input.jsx
  src/components/signup/atoms/Label.jsx
  src/components/signup/atoms/LinkButton.jsx
  src/components/signup/molecules/AlertBox.jsx
  src/components/signup/molecules/InputGroup.jsx
  src/hooks/.gitkeep
  src/hooks/useInput.js
  src/layouts/.gitkeep
  src/layouts/OnlyOutletLayout.jsx
  src/pages/.gitkeep
  src/pages/SignupPage.jsx
Labels: ✨ Feature

#16 로그인 페이지 구현 & GNB 영역 Fix
  src/App.js
  src/components/common/GNBBOX.jsx
  src/components/signup/atoms/Input.jsx
  src/components/signup/molecules/InputGroup.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
Labels: ✨ Feature

#23 회원가입 페이지 보완
  src/pages/SignupPage.jsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#25 폴더구조 리팩토링
  src/components/common/BottomSheet.jsx
  src/components/common/accounts/AlertBox.jsx
  src/components/common/accounts/InputGroup.jsx
  src/components/common/atoms/Box.jsx
  src/components/common/atoms/Button.jsx
  src/components/common/atoms/Container.jsx
  src/components/common/atoms/Input.jsx
  src/components/common/atoms/Label.jsx
  src/components/common/atoms/LinkButton.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/components/profile/ProfileTemplate.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/store/slices/userSlice.js
Labels: 🔨 Refactor, 🥰 Accessibility

#27 CRLF 관련 prettier 에러 수정 및 prettier 규칙 적용
  .eslintrc.json
  src/components/common/accounts/InputGroup.jsx
  src/components/common/atoms/Input.jsx
  src/index.js
  src/mocks/browser.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationHandler.js
  src/mocks/userHandler.js
  src/reportWebVitals.js
  src/setupTests.js
  src/store/slices/userSlice.js
Labels: ⚙ Setting

#29 결제 연동(토스페이먼츠)
  package-lock.json
  package.json
  src/App.js
  src/apis/payments.js
  src/components/profile/MembershipBottomSheet.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/components/profile/ProfileTemplate.jsx
  src/mocks/browser.js
  src/mocks/paymentHandler.js
  src/mocks/requestData.js
  src/mocks/responseData.js
  src/pages/LoginPage.jsx
  src/pages/PaymentCompletePage.jsx
  src/pages/PaymentFailPage.jsx
  src/pages/PaymentPage.jsx
  src/utils/.gitkeep
  src/utils/constants.js
  src/utils/convert.js
Labels: ✨ Feature, 📬 API

#31 포트폴리오 탐색 페이지 구현
  .gitignore
  public/images/1.jpg
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  src/apis/portfolio.js
  src/components/common/GNB.jsx
  src/components/common/atoms/Card.jsx
  src/components/common/atoms/Photo.jsx
  src/components/common/atoms/SkeletonCard.jsx
  src/components/common/atoms/SquarePhoto.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioGrid.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/hooks/useFetchPortfolios.js
  src/pages/PaymentPage.jsx
  src/pages/SearchPage.jsx
Labels: ⚙ Setting, ✨ Feature, 🎨 HTML&CSS

#13 부산대_5조_순수웨딩_4주차
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/mockServiceWorker.js
  public/robots.txt
  src/App.js
  src/App.test.js
  src/apis/index.js
  src/apis/portfolio.js
  src/apis/quotation.js
  src/apis/user.js
  src/assets/chat-01.svg
  src/assets/chat-02.svg
  src/assets/home-01.svg
  src/assets/home-02.svg
  src/assets/profile-01.svg
  src/assets/profile-02.svg
  src/assets/search-01.svg
  src/assets/search-02.svg
  src/components/common/GNB.jsx
  src/components/signup/atoms/Box.jsx
  src/components/signup/atoms/Button.jsx
  src/components/signup/atoms/Container.jsx
  src/components/signup/atoms/Input.jsx
  src/components/signup/atoms/Label.jsx
  src/components/signup/atoms/LinkButton.jsx
  src/components/signup/molecules/AlertBox.jsx
  src/components/signup/molecules/InputGroup.jsx
  src/hooks/useInput.js
  src/index.css
  src/index.js
  src/layouts/MainLayout.jsx
  src/layouts/OnlyOutletLayout.jsx
  src/mocks/browser.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationHandler.js
  src/mocks/requestData.js
  src/mocks/responseData.js
  src/mocks/userHandler.js
  src/pages/ChatListPage.jsx
  src/pages/MainPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/store/.gitkeep
  src/utils/.gitkeep
  tailwind.config.js
Labels: 💯 RequestReview

#41 GNB sticky & BottomSheet, 마이페이지 디자인 변경
  src/components/common/BottomSheet.jsx
  src/components/common/GNB.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/profile/MembershipBottomSheet.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/components/profile/ProfileTemplate.jsx
  src/layouts/MainLayout.jsx
Labels: 🎨 HTML&CSS, 🐞 BugFix

#43 GNB position Fixed 변경
  src/components/common/BottomSheet.jsx
  src/components/common/GNB.jsx
  src/components/common/GNBBOX.jsx
  src/components/portfolios/PortfolioGrid.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/layouts/MainLayout.jsx
  src/mocks/responseData.js
  src/pages/SearchPage.jsx
Labels: 🎨 HTML&CSS

#50 캐러셀 구현
  package-lock.json
  package.json
  src/components/portfolios/PortfolioCarousel.css
  src/components/portfolios/PortfolioCarousel.jsx
  src/components/portfolios/PortfolioDetailTemplate.jsx
  src/pages/PortfolioDetailPage.jsx
Labels: ✨ Feature

#51 메인페이지 구현
  src/assets/chat-01.svg
  src/assets/chat-02.svg
  src/assets/home-01.svg
  src/assets/home-02.svg
  src/assets/profile-01.svg
  src/assets/profile-02.svg
  src/assets/search-01.svg
  src/assets/search-02.svg
  src/components/common/GNB.jsx
  src/components/main/MainCarousel.css
  src/components/main/MainCarousel.jsx
  src/components/main/MainPhoto.jsx
  src/pages/MainPage.jsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 HTML&CSS

#56 채팅 구현 및 api 수정
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App.js
  src/apis/chat.js
  src/apis/portfolio.js
  src/components/chat/ChatHeader.jsx
  src/components/chat/ChatInput.jsx
  src/components/chat/ChatMessage.jsx
  src/components/chat/ChatRoomItem.jsx
  src/components/chat/DateSeperationLine.jsx
  src/components/common/BottomSheet.jsx
  src/components/common/GNB.jsx
  src/components/common/Modal/ImageModal.jsx
  src/components/portfolios/HistoryBottomSheet.jsx
  src/components/portfolios/PortfolioCarousel.jsx
  src/components/portfolios/PortfolioDetailTemplate.jsx
  src/components/portfolios/PriceInfoRow.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/profile/MembershipBottomSheet.jsx
  src/components/profile/PaymentBottomSheet.jsx
  src/components/profile/ProfileTemplate.jsx
  src/firebase/index.js
  src/hooks/useFetchPortfolios.js
  src/layouts/MainLayout.jsx
  src/mocks/browser.js
  src/mocks/chatData.js
  src/mocks/chatHandler.js
  src/mocks/commonData.js
  src/mocks/matchData.js
  src/mocks/matchHandler.js
  src/mocks/paymentHandler.js
  src/mocks/paymentsData.js
  src/mocks/portfolioData.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationData.js
  src/mocks/quotationHandler.js
  src/mocks/responseData.js
  src/mocks/userData.js
  src/mocks/userHandler.js
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/MainPage.jsx
  src/pages/PaymentCompletePage.jsx
  src/pages/PortfolioDetailPage.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
  src/utils/convert.js
Labels: ✨ Feature, 🎨 HTML&CSS

#62 가로 스크롤 숨김 & 디자인 수정
  src/components/chat/ChatListHeaderRow.jsx
  src/components/chat/ChatRoomItem.jsx
  src/components/common/atoms/Spinner.jsx
  src/components/main/MainHeaderRow.jsx
  src/components/main/MainPhoto.jsx
  src/components/portfolios/DescriptionRow.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioCarousel.jsx
  src/components/portfolios/PortfolioDetailTemplate.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/portfolios/PriceInfoRow.jsx
  src/components/portfolios/SearchHeaderRow.jsx
  src/components/profile/ProfileTemplate.jsx
  src/index.css
  src/layouts/MainLayout.jsx
  src/layouts/OnlyOutletLayout.jsx
  src/pages/ChatListPage.jsx
  src/pages/MainPage.jsx
Labels: 🎨 HTML&CSS

#73 디자인 수정
  src/assets/close-01.svg
  src/assets/close-02.svg
  src/assets/emoji-01.svg
  src/assets/gallery-01.svg
  src/assets/left-01.svg
  src/assets/search-03.svg
  src/assets/send-01.svg
  src/components/chat/ChatHeader.jsx
  src/components/chat/ChatInput.jsx
  src/components/chat/ChatListHeaderRow.jsx
  src/components/chat/ChatMessage.jsx
  src/components/common/BackButtonHeader.jsx
  src/components/common/HeaderRow.jsx
  src/components/common/SearchBar.jsx
  src/components/common/bottomsheet/BottomSheet.jsx
  src/components/common/modal/ImageModal.jsx
  src/components/main/MainHeaderRow.jsx
  src/components/portfoliodetail/PortfolioDetailHeader.jsx
  src/components/portfolios/SearchHeaderRow.jsx
  src/pages/ChatRoomPage.jsx
Labels: 🎨 HTML&CSS

#84 프로필 이미지 연동
  package-lock.json
  package.json
  public/images/default-avatar.jpeg
  src/App.js
  src/apis/index.js
  src/components/chat/ChatInput.jsx
  src/components/chat/ChatMessage.jsx
  src/components/chat/ChatRoomItem.jsx
  src/components/common/SearchBar.jsx
  src/components/common/TextWithNewlines.jsx
  src/components/common/modal/ProfileImageModal.jsx
  src/components/main/MainSearchBar.jsx
  src/components/profile/ProfileImage.jsx
  src/components/profile/ProfileImageSpinner.jsx
  src/components/profile/ProfileTemplate.jsx
  src/components/profile/profileImageSpinner.css
  src/layouts/MainLayout.jsx
  src/layouts/RequiredAuthLayout.jsx
  src/mocks/chatHandler.js
  src/mocks/userHandler.js
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/CreatePortfolioPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/PortfolioDetailPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
  src/store/slices/userSlice.js
  src/utils/constants.js
  src/utils/convert.js
  tailwind.config.js
Labels: ✨ Feature, 🎨 HTML&CSS

#88 미디어 쿼리 재적용 & 이용약관 및 개인정보 처리방침 페이지 구현
  .eslintrc.json
  src/App.js
  src/components/main/MainCarousel.jsx
  src/components/main/MainPhoto.jsx
  src/components/portfoliodetail/PortfolioCarousel.jsx
  src/pages/PrivacyPolicyPage.jsx
  src/pages/SignupPage.jsx
  src/pages/TermsPage.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#92 뒤로가기, 새로고침을 막는 커스텀 훅 제작
  src/components/common/accounts/InputGroup.jsx
  src/hooks/usePreventGoBack.js
  src/hooks/usePreventRefresh.js
  src/pages/CreatePortfolioPage.jsx
Labels: ✨ Feature
