Repository Step3-kakao-tech-campus/Team5_FE, pull requests merged in 2023-09, with the labels that each got.

#4 Initialize sunsu-wedding
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/apis/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/hooks/.gitkeep
  src/index.css
  src/index.js
  src/layouts/.gitkeep
  src/pages/.gitkeep
  src/reportWebVitals.js
  src/setupTests.js
  src/store/.gitkeep
  src/utils/.gitkeep
  tailwind.config.js
Labels: ✨ Feature

#6 API Mocking 및 초기 라우트 설정
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.js
  src/App.test.js
  src/apis/index.js
  src/apis/portfolio.js
  src/apis/quotation.js
  src/apis/user.js
  src/components/common/GNB.jsx
  src/index.js
  src/layouts/MainLayout.jsx
  src/mocks/browser.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationHandler.js
  src/mocks/requestData.js
  src/mocks/responseData.js
  src/mocks/userHandler.js
  src/pages/ChatListPage.jsx
  src/pages/MainPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SearchPage.jsx
Labels: ⚙ Setting, ✨ Feature, 📬 API

#8 GNB 아이콘 변경
  src/assets/chat-01.svg
  src/assets/chat-02.svg
  src/assets/home-01.svg
  src/assets/home-02.svg
  src/assets/profile-01.svg
  src/assets/profile-02.svg
  src/assets/search-01.svg
  src/assets/search-02.svg
  src/components/common/GNB.jsx
Labels: 🎨 HTML&CSS
