Repository Step3-kakao-tech-campus/Team5_FE, pull requests merged in 2023-11, with the labels that each got.

#93 견적서 기능 구현
  src/App.js
  src/apis/quotation.js
  src/assets/add-01.svg
  src/assets/star-01.svg
  src/components/chat/ChatHeader.jsx
  src/components/common/atoms/AutoHeightTextarea.jsx
  src/components/quotation/ConfirmAllBottomSheet.jsx
  src/components/quotation/ConfirmOneBottomSheet.jsx
  src/components/quotation/QuotationCreateHeader.jsx
  src/components/quotation/QuotationListHeader.jsx
  src/components/quotation/QuotationListTemplate.jsx
  src/components/quotation/QuotationUpdateHeader.jsx
  src/mocks/quotationData.js
  src/mocks/quotationHandler.js
  src/pages/ChatRoomPage.jsx
  src/pages/QuotationCreatePage.jsx
  src/pages/QuotationListPage.jsx
  src/pages/QuotationUpdatePage.jsx
  src/store/atoms/index.js
  src/store/atoms/quotation.js
  src/utils/convert.js
Labels: ✨ Feature

#94 FilterForm 구현
  src/components/common/TextareaGroup.jsx
  src/components/common/atoms/AutoHeightTextarea.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/createportfolio/PortfolioImage.jsx
  src/components/createportfolio/SelectRegion.jsx
  src/components/createportfolio/SuccessBottomSheet.jsx
  src/components/portfolios/EmptySearchResult.jsx
  src/components/portfolios/FilterForm.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/portfolios/RangeSlider.jsx
  src/components/portfolios/SearchHeaderRow.jsx
  src/hooks/usePreventGoBack.js
  src/mocks/encodingImages.js
  src/mocks/portfolioData.js
  src/mocks/portfolioHandler.js
  src/pages/QuotationCreatePage.jsx
  src/utils/constants.js
Labels: ✨ Feature

#96 리뷰 작성 페이지 구현
  src/App.js
  src/apis/review.js
  src/components/chat/ChatHeader.jsx
  src/components/common/ImageUploadZone.jsx
  src/components/common/accounts/InputGroup.jsx
  src/components/common/atoms/AutoHeightTextarea.jsx
  src/components/common/atoms/Input.jsx
  src/components/common/bottomsheet/GlobalBottomSheet.jsx
  src/components/common/bottomsheet/NavigateReviewBottomSheet.jsx
  src/components/common/bottomsheet/SuccessBottomSheet.jsx
  src/components/common/bottomsheet/WarningBottomSheet.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/quotation/ConfirmAllBottomSheet.jsx
  src/components/quotation/QuotationListTemplate.jsx
  src/components/quotation/RequiredConfirmBottomSheet.jsx
  src/components/review/ReviewCreateHeader.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/mocks/browser.js
  src/mocks/commonData.js
  src/mocks/paymentHandler.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationHandler.js
  src/mocks/reviewHandler.js
  src/mocks/userHandler.js
  src/pages/ReviewCreatePage.jsx
  src/utils/handleBottomSheet.js
Labels: ✨ Feature, 🎨 HTML&CSS

#99 폰트 변경 & 견적서 모아보기 기능 구현
  src/App.js
  src/apis/quotation.js
  src/assets/filter-01.svg
  src/assets/filter-02.svg
  src/components/main/InProgressQuotationBanner.jsx
  src/components/portfolios/PortfolioGrid.jsx
  src/components/portfolios/RangeSlider.jsx
  src/components/portfolios/SearchHeaderRow.jsx
  src/components/profile/ProfileTemplate.jsx
  src/components/quotation/QuotationCollectHeader.jsx
  src/components/quotation/QuotationCollectTemplate.jsx
  src/components/quotation/SkeletonQuotationItem.jsx
  src/hooks/useFetchQuotationCollect.js
  src/index.css
  src/mocks/quotationData.js
  src/mocks/quotationHandler.js
  src/pages/MainPage.jsx
  src/pages/QuotationCollectPage.jsx
  src/pages/QuotationCreatePage.jsx
  src/pages/QuotationUpdatePage.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#101 찜한 플래너 모아보기 기능 구현
  src/App.js
  src/apis/favorite.js
  src/assets/heart-03.svg
  src/assets/heart-04.svg
  src/components/favorite/FavoriteListHeader.jsx
  src/components/favorite/FavoriteListTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/profile/ProfileTemplate.jsx
  src/hooks/useFetchFavorites.js
  src/mocks/browser.js
  src/mocks/favoriteData.js
  src/mocks/favoriteHandler.js
  src/pages/FavoriteListPage.jsx
Labels: ✨ Feature

#103 변경된 견적서 모아보기 API 적용
  src/components/main/InProgressQuotationBanner.jsx
  src/components/quotation/QuotationCollectTemplate.jsx
  src/components/quotation/SkeletonQuotationItem.jsx
  src/hooks/useFetchQuotationCollect.js
  src/mocks/quotationData.js
  src/mocks/quotationHandler.js
Labels: ✨ Feature

#112 HEIC 이미지 파일 업로드 & 이미지 압축 구현
  package-lock.json
  package.json
  public/images/star.png
  src/assets/star-02.svg
  src/assets/star-03.svg
  src/components/chat/ChatRoomItem.jsx
  src/components/common/ImageUploadZone.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/profile/ProfileImage.jsx
  src/components/review/PortfolioReviewItem.jsx
  src/components/review/ReviewCreateHeader.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/components/review/ReviewListTemplate.jsx
  src/components/review/ReviewUpdateHeader.jsx
  src/components/review/ReviewUpdateTemplate.jsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐞 BugFix, ⚡️ Performance

#118 파비콘 & 견적서 삭제 구현
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.svg
  public/index.html
  public/manifest.json
  public/mask-icon.svg
  src/apis/quotation.js
  src/components/main/MainHeaderRow.jsx
  src/components/quotation/DeleteOneBottomSheet.jsx
  src/components/quotation/QuotationCollectTemplate.jsx
  src/components/quotation/QuotationListTemplate.jsx
  src/index.css
  src/mocks/quotationHandler.js
Labels: ✨ Feature, 🎨 HTML&CSS

#121 리뷰 평점 평균 & 리뷰 조회 이미지 캐러셀 구현
  src/components/main/MainCarousel.jsx
  src/components/portfoliodetail/PortfolioCarousel.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/review/PortfoliioReviewTemplate.jsx
  src/components/review/PortfolioReviewItem.css
  src/components/review/PortfolioReviewItem.jsx
  src/mocks/portfolioData.js
  src/mocks/reviewData.js
Labels: ✨ Feature, 🎨 HTML&CSS, ⚡️ Performance

#128 로그인 되어있는 경우 로그인 및 회원가입 페이지 접근 제한 & API URL 변경
  src/App.js
  src/apis/chat.js
  src/apis/email.js
  src/apis/favorite.js
  src/apis/payments.js
  src/apis/portfolio.js
  src/apis/quotation.js
  src/apis/review.js
  src/apis/user.js
  src/assets/logo-01.svg
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/review/PortfolioReviewSkeleton.jsx
  src/layouts/DuplicatedCheckLayout.jsx
  src/mocks/chatHandler.js
  src/mocks/favoriteHandler.js
  src/mocks/paymentHandler.js
  src/mocks/portfolioHandler.js
  src/mocks/quotationHandler.js
  src/mocks/reviewHandler.js
  src/mocks/userHandler.js
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
Labels: 🎨 HTML&CSS, 🐞 BugFix, 📬 API

#129 채팅 입력창 최대 높이 지정
  src/components/chat/ChatInput.jsx
  src/components/common/atoms/AutoHeightTextarea.jsx
Labels: 🎨 HTML&CSS

#133 1차 리팩토링
  src/apis/index.js
  src/apis/user.js
  src/components/common/bottomsheet/GlobalBottomSheet.jsx
  src/components/common/bottomsheet/MessageBottomSheet.jsx
  src/components/common/bottomsheet/PaymentBottomSheet.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/createportfolio/ItemsInfo.jsx
  src/components/createportfolio/UpdatePortfolioTemplate.jsx
  src/components/main/InProgressQuotationBanner.jsx
  src/components/portfoliodetail/MembershipPaySection.jsx
  src/components/portfoliodetail/PaymentsHistorySection.jsx
  src/components/portfoliodetail/PlannerInfoRow.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioSearchBar.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/profile/DeletePortfolioBottomSheet.jsx
  src/components/quotation/AlreadyConfirmBottomSheet.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/components/review/ReviewUpdateTemplate.jsx
  src/hooks/useDefaultErrorHander.js
  src/hooks/useFetchPortfolios.js
  src/pages/CreatePortfolioPage.jsx
  src/pages/LoginPage.jsx
  src/pages/PaymentCompletePage.jsx
  src/pages/PortfolioDetailPage.jsx
  src/pages/QuotationCreatePage.jsx
  src/pages/QuotationUpdatePage.jsx
  src/pages/SignupPage.jsx
  src/store/slices/bottomSheetSlice.js
  src/utils/convert.js
  src/utils/handleBottomSheet.js
Labels: 🐞 BugFix, 🔨 Refactor

#135 포트폴리오 생성 템플릿 데이터 & 회원가입 페이지 수정
  src/components/common/CloseButtonPage.jsx
  src/components/common/PrivacyPolicyData.jsx
  src/components/common/TermsData.jsx
  src/components/common/bottomsheet/PaymentBottomSheet.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/main/MainHeaderRow.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/hooks/useDefaultErrorHandler.js
  src/hooks/useScrollToTop.js
  src/pages/CreatePortfolioPage.jsx
  src/pages/LoginPage.jsx
  src/pages/PaymentCompletePage.jsx
  src/pages/PortfolioDetailPage.jsx
  src/pages/PrivacyPolicyPage.jsx
  src/pages/SignupPage.jsx
  src/pages/TermsPage.jsx
  src/utils/convert.js
Labels: 🐞 BugFix

#137 README & index.html 수정
  README.md
  public/index.html
Labels: 🎨 HTML&CSS, 📃 Docs

#138 메일 인증 로직 추가
  src/apis/portfolio.js
  src/components/chat/ChatInput.jsx
  src/components/chat/ChatMessage.jsx
  src/components/chat/ChatRoomItem.jsx
  src/components/common/GNB.jsx
  src/components/common/bottomsheet/GlobalBottomSheet.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/createportfolio/ItemsInfo.jsx
  src/components/createportfolio/UpdatePortfolioTemplate.jsx
  src/components/portfoliodetail/FavoriteButton.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/components/portfolios/FilterForm.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/profile/DeletePortfolioBottomSheet.jsx
  src/components/profile/PortfolioSection.jsx
  src/components/profile/ProfileImage.jsx
  src/components/profile/ProfileImageSpinner.jsx
  src/components/profile/ProfileTemplate.jsx
  src/components/profile/ReviewSection.jsx
  src/components/quotation/ConfirmAllBottomSheet.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/components/review/ReviewUpdateHeader.jsx
  src/components/review/ReviewUpdateTemplate.jsx
  src/hooks/useChatRoom.js
  src/hooks/useDefaultErrorHandler.js
  src/hooks/useOpenBottomSheet.js
  src/mocks/chatHandler.js
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/CreatePortfolioPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignupPage.jsx
  src/utils/handleBottomSheet.js
Labels: 🐞 BugFix, 🔨 Refactor

#141 찜하기 모아보기 삭제 렌더링 버그 해결
  src/components/common/accounts/InputGroup.jsx
  src/components/common/atoms/Input.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/createportfolio/UpdatePortfolioTemplate.jsx
  src/components/favorite/FavoriteListTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/portfolios/PortfolioGrid.jsx
  src/components/quotation/ConfirmAllBottomSheet.jsx
  src/hooks/useFetchFavorites.js
  src/hooks/useFetchPortfolios.js
  src/index.js
  src/pages/ReviewCreatePage.jsx
  src/pages/ReviewUpdatePage.jsx
  src/pages/SignupPage.jsx
Labels: 🐞 BugFix

#143 렌더링 버그 및 기타 옵션 수정
  src/components/common/ImageUploadZone.jsx
  src/components/portfoliodetail/PaymentsHistorySection.jsx
  src/components/portfoliodetail/PortfolioDetailTemplate.jsx
  src/hooks/useFetchPortfolioReviews.js
  src/mocks/portfolioData.js
Labels: 🐞 BugFix

#145 찜하기 삭제 버그 Fix & 등록 / 수정 완료시 라우팅
  src/App.js
  src/apis/index.js
  src/components/common/bottomsheet/GlobalBottomSheet.jsx
  src/components/common/bottomsheet/RouteBottomSheet.jsx
  src/components/createportfolio/CreatePortfolioTemplate.jsx
  src/components/createportfolio/UpdatePortfolioTemplate.jsx
  src/components/portfolios/PortfolioCard.jsx
  src/components/profile/ProfileTemplate.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/components/review/ReviewUpdateTemplate.jsx
  src/hooks/useFetchFavorites.js
Labels: 🐞 BugFix

#147 리뷰 수정 시 이전 수정 내역이 렌더링 되는 현상 수정
  src/components/common/ImageUploadZone.jsx
  src/components/review/ReviewUpdateTemplate.jsx
  src/pages/ReviewUpdatePage.jsx
Labels: 🐞 BugFix

#150 리뷰 관리 페이지 캐러셀 적용 & 포트폴리오 수정 시 렌더링 오류 수정
  src/apis/index.js
  src/components/review/PortfolioReviewTemplate.jsx
  src/components/review/ReviewImageCarousel.jsx
  src/components/review/ReviewListHeader.jsx
  src/components/review/ReviewListTemplate.jsx
  src/pages/CreatePortfolioPage.jsx
  src/pages/LoginPage.jsx
  src/pages/PortfolioReviewPage.jsx
  src/pages/SignupPage.jsx
Labels: 🐞 BugFix

#152 채팅방 코드 리팩토링
  src/components/favorite/FavoriteListTemplate.jsx
  src/components/portfolios/PortfolioGrid.jsx
  src/components/portfolios/PortfolioTemplate.jsx
  src/components/profile/DeleteAccountBottomSheet.jsx
  src/components/quotation/NoQuotationCollect.jsx
  src/components/review/NoPortfolioReview.jsx
  src/components/review/NoReviewList.jsx
  src/hooks/useChatRoom.js
  src/pages/ChatRoomPage.jsx
  src/utils/firebase.js
Labels: 🔨 Refactor

#153 PWA 설정
  public/index.html
  public/manifest.json
  public/offline.html
  public/service-worker.js
Labels: 🌏 Deploy

#154 UX 수정
  public/manifest.json
  src/apis/index.js
  src/components/profile/DeletePortfolioBottomSheet.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/PaymentCompletePage.jsx
  src/pages/PaymentFailPage.jsx
  src/pages/SignupPage.jsx
Labels: 🐞 BugFix

#156 이미지 압축 미지원 브라우저 알림 추가 & UX 수정
  src/components/common/ImageUploadZone.jsx
  src/components/createportfolio/ItemsInfo.jsx
  src/components/quotation/QuotationCollectTemplate.jsx
  src/components/quotation/QuotationListTemplate.jsx
  src/components/review/ReviewCreateTemplate.jsx
  src/components/review/ReviewUpdateTemplate.jsx
  src/pages/QuotationCreatePage.jsx
  src/pages/QuotationUpdatePage.jsx
  src/utils/constants.js
Labels: 🐞 BugFix

#157 UX 수정
  public/images/1_1.png
  public/images/1_6.png
  public/images/2_1.png
  public/images/2_6.png
  public/index.html
  src/assets/congratulations-01.svg
  src/assets/logo-02.svg
  src/components/common/bottomsheet/RequiredLoginBottomSheet.jsx
  src/components/main/MainBestReview.jsx
  src/components/main/MainCarousel.jsx
  src/components/main/MainHeaderRow.jsx
  src/components/main/MainPhoto.jsx
  src/components/quotation/NoQuotationListTemplate.jsx
  src/components/quotation/QuotationListTemplate.jsx
  src/index.css
Labels: 🐞 BugFix

#159 README 수정
  README.md
Labels: 📃 Docs
